// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/cart/v1/cart.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 购物车项信息
type CartReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Selected      bool                   `protobuf:"varint,5,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartReply) Reset() {
	*x = CartReply{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartReply) ProtoMessage() {}

func (x *CartReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartReply.ProtoReflect.Descriptor instead.
func (*CartReply) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartReply) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartReply) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartReply) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

type AddCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartRequest) Reset() {
	*x = AddCartRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartRequest) ProtoMessage() {}

func (x *AddCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartRequest.ProtoReflect.Descriptor instead.
func (*AddCartRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCartRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Selected      bool                   `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartRequest) Reset() {
	*x = UpdateCartRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartRequest) ProtoMessage() {}

func (x *UpdateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCartRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateCartRequest) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

type DeleteCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartRequest) Reset() {
	*x = DeleteCartRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartRequest) ProtoMessage() {}

func (x *DeleteCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCartRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCartRequest) Reset() {
	*x = ListCartRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartRequest) ProtoMessage() {}

func (x *ListCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartRequest.ProtoReflect.Descriptor instead.
func (*ListCartRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{4}
}

func (x *ListCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListCartReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CartReply           `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCartReply) Reset() {
	*x = ListCartReply{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartReply) ProtoMessage() {}

func (x *ListCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartReply.ProtoReflect.Descriptor instead.
func (*ListCartReply) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *ListCartReply) GetResults() []*CartReply {
	if x != nil {
		return x.Results
	}
	return nil
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{6}
}

func (x *ClearCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_api_cart_v1_cart_proto protoreflect.FileDescriptor

const file_api_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x16api/cart/v1/cart.proto\x12\acart.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x8b\x01\n" +
	"\tCartReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bselected\x18\x05 \x01(\bR\bselected\"d\n" +
	"\x0eAddCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"[\n" +
	"\x11UpdateCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bselected\x18\x03 \x01(\bR\bselected\"#\n" +
	"\x11DeleteCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"*\n" +
	"\x0fListCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"=\n" +
	"\rListCartReply\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.cart.v1.CartReplyR\aresults\"+\n" +
	"\x10ClearCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId2\xc3\x02\n" +
	"\vCartService\x126\n" +
	"\aAddCart\x12\x17.cart.v1.AddCartRequest\x1a\x12.cart.v1.CartReply\x12<\n" +
	"\n" +
	"UpdateCart\x12\x1a.cart.v1.UpdateCartRequest\x1a\x12.cart.v1.CartReply\x12@\n" +
	"\n" +
	"DeleteCart\x12\x1a.cart.v1.DeleteCartRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\bListCart\x12\x18.cart.v1.ListCartRequest\x1a\x16.cart.v1.ListCartReply\x12>\n" +
	"\tClearCart\x12\x19.cart.v1.ClearCartRequest\x1a\x16.google.protobuf.EmptyB\x1dZ\x1bcart-service/api/cart/v1;v1b\x06proto3"

var (
	file_api_cart_v1_cart_proto_rawDescOnce sync.Once
	file_api_cart_v1_cart_proto_rawDescData []byte
)

func file_api_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_api_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_api_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cart_v1_cart_proto_rawDesc), len(file_api_cart_v1_cart_proto_rawDesc)))
	})
	return file_api_cart_v1_cart_proto_rawDescData
}

var file_api_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_cart_v1_cart_proto_goTypes = []any{
	(*CartReply)(nil),         // 0: cart.v1.CartReply
	(*AddCartRequest)(nil),    // 1: cart.v1.AddCartRequest
	(*UpdateCartRequest)(nil), // 2: cart.v1.UpdateCartRequest
	(*DeleteCartRequest)(nil), // 3: cart.v1.DeleteCartRequest
	(*ListCartRequest)(nil),   // 4: cart.v1.ListCartRequest
	(*ListCartReply)(nil),     // 5: cart.v1.ListCartReply
	(*ClearCartRequest)(nil),  // 6: cart.v1.ClearCartRequest
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_api_cart_v1_cart_proto_depIdxs = []int32{
	0, // 0: cart.v1.ListCartReply.results:type_name -> cart.v1.CartReply
	1, // 1: cart.v1.CartService.AddCart:input_type -> cart.v1.AddCartRequest
	2, // 2: cart.v1.CartService.UpdateCart:input_type -> cart.v1.UpdateCartRequest
	3, // 3: cart.v1.CartService.DeleteCart:input_type -> cart.v1.DeleteCartRequest
	4, // 4: cart.v1.CartService.ListCart:input_type -> cart.v1.ListCartRequest
	6, // 5: cart.v1.CartService.ClearCart:input_type -> cart.v1.ClearCartRequest
	0, // 6: cart.v1.CartService.AddCart:output_type -> cart.v1.CartReply
	0, // 7: cart.v1.CartService.UpdateCart:output_type -> cart.v1.CartReply
	7, // 8: cart.v1.CartService.DeleteCart:output_type -> google.protobuf.Empty
	5, // 9: cart.v1.CartService.ListCart:output_type -> cart.v1.ListCartReply
	7, // 10: cart.v1.CartService.ClearCart:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_cart_v1_cart_proto_init() }
func file_api_cart_v1_cart_proto_init() {
	if File_api_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cart_v1_cart_proto_rawDesc), len(file_api_cart_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_api_cart_v1_cart_proto_depIdxs,
		MessageInfos:      file_api_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_api_cart_v1_cart_proto = out.File
	file_api_cart_v1_cart_proto_goTypes = nil
	file_api_cart_v1_cart_proto_depIdxs = nil
}
