// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/internal/client"
	"gateway/internal/conf"
	"gateway/internal/server"
	"gateway/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	clients, err := client.NewClients(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	gatewayService := service.NewGatewayService(clients, logger)
	httpServer := server.NewHTTPServer(bootstrap, gatewayService, logger)
	app := newApp(httpServer, logger)
	return app, func() {
	}, nil
}
