// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/internal/client"
	"gateway/internal/conf"
	"gateway/internal/server"
	"gateway/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

func wireApp(cfg *conf.Config, logger log.Logger, tracer trace.Tracer) (*kratos.App, func(), error) {
	clients, err := client.NewClients(cfg)
	if err != nil {
		return nil, nil, err
	}
	gatewayService := service.NewGatewayService(clients, logger)
	httpServer := server.NewHTTPServer(cfg, gatewayService, logger, tracer)
	app := newApp(httpServer, logger)
	return app, func() {
	}, nil
}
