// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cart-service/internal/biz"
	"cart-service/internal/conf"
	"cart-service/internal/data"
	"cart-service/internal/server"
	"cart-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(config *conf.Config, logger log.Logger) (*kratos.App, func(), error) {
	confData := data.ProvideDataConfig(config)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	cartRepo := data.NewCartRepo(dataData, logger)
	discovery := data.NewDiscovery(config)
	string2 := data.ProvideProductEndpoint(config)
	productRepo := data.NewProductRepo(discovery, string2, logger)
	cartUseCase := biz.NewCartUseCase(cartRepo, productRepo, logger)
	cartService := service.NewCartService(cartUseCase)
	grpcServer := server.NewGRPCServer(config, cartService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
