// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/payment/v1/payment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付状态
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1 // 待支付
	PaymentStatus_PAYMENT_STATUS_SUCCESS     PaymentStatus = 2 // 支付成功
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3 // 支付失败
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4 // 已退款
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_SUCCESS",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_SUCCESS":     2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_api_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payment.v1.PaymentStatus" json:"status,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,6,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"` // 预支付链接（如果是扫码支付等）
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReply) Reset() {
	*x = PaymentReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReply) ProtoMessage() {}

func (x *PaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReply.ProtoReflect.Descriptor instead.
func (*PaymentReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentReply) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentReply) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentReply) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *PaymentReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentReply) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type PaymentCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment.v1.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 三方交易流水号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackRequest) Reset() {
	*x = PaymentCallbackRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackRequest) ProtoMessage() {}

func (x *PaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*PaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentCallbackRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentCallbackRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentCallbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *RefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payment/v1/payment.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb7\x02\n" +
	"\fPaymentReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.payment.v1.PaymentStatusR\x06status\x12\x1f\n" +
	"\vpayment_url\x18\x06 \x01(\tR\n" +
	"paymentUrl\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"e\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\x91\x01\n" +
	"\x16PaymentCallbackRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.payment.v1.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"^\n" +
	"\rRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*\x9f\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_STATUS_SUCCESS\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x042\xb2\x02\n" +
	"\x0ePaymentService\x12K\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a\x18.payment.v1.PaymentReply\x12E\n" +
	"\n" +
	"GetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x18.payment.v1.PaymentReply\x12M\n" +
	"\x0fPaymentCallback\x12\".payment.v1.PaymentCallbackRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x06Refund\x12\x19.payment.v1.RefundRequest\x1a\x18.payment.v1.PaymentReplyB#Z!payment-service/api/payment/v1;v1b\x06proto3"

var (
	file_api_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_payment_v1_payment_proto_rawDescData []byte
)

func file_api_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_payment_v1_payment_proto_rawDescData
}

var file_api_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_payment_v1_payment_proto_goTypes = []any{
	(PaymentStatus)(0),             // 0: payment.v1.PaymentStatus
	(*PaymentReply)(nil),           // 1: payment.v1.PaymentReply
	(*CreatePaymentRequest)(nil),   // 2: payment.v1.CreatePaymentRequest
	(*GetPaymentRequest)(nil),      // 3: payment.v1.GetPaymentRequest
	(*PaymentCallbackRequest)(nil), // 4: payment.v1.PaymentCallbackRequest
	(*RefundRequest)(nil),          // 5: payment.v1.RefundRequest
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_api_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentReply.status:type_name -> payment.v1.PaymentStatus
	6, // 1: payment.v1.PaymentReply.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: payment.v1.PaymentReply.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: payment.v1.PaymentCallbackRequest.status:type_name -> payment.v1.PaymentStatus
	2, // 4: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	3, // 5: payment.v1.PaymentService.GetPayment:input_type -> payment.v1.GetPaymentRequest
	4, // 6: payment.v1.PaymentService.PaymentCallback:input_type -> payment.v1.PaymentCallbackRequest
	5, // 7: payment.v1.PaymentService.Refund:input_type -> payment.v1.RefundRequest
	1, // 8: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.PaymentReply
	1, // 9: payment.v1.PaymentService.GetPayment:output_type -> payment.v1.PaymentReply
	7, // 10: payment.v1.PaymentService.PaymentCallback:output_type -> google.protobuf.Empty
	1, // 11: payment.v1.PaymentService.Refund:output_type -> payment.v1.PaymentReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_payment_v1_payment_proto_init() }
func file_api_payment_v1_payment_proto_init() {
	if File_api_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_api_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_api_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_payment_v1_payment_proto = out.File
	file_api_payment_v1_payment_proto_goTypes = nil
	file_api_payment_v1_payment_proto_depIdxs = nil
}
