// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/promotion/v1/promotion.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromotionService_CreateCoupon_FullMethodName      = "/promotion.v1.PromotionService/CreateCoupon"
	PromotionService_ListCoupons_FullMethodName       = "/promotion.v1.PromotionService/ListCoupons"
	PromotionService_GrantCoupon_FullMethodName       = "/promotion.v1.PromotionService/GrantCoupon"
	PromotionService_UseCoupon_FullMethodName         = "/promotion.v1.PromotionService/UseCoupon"
	PromotionService_CalculateDiscount_FullMethodName = "/promotion.v1.PromotionService/CalculateDiscount"
)

// PromotionServiceClient is the client API for PromotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 营销服务定义
type PromotionServiceClient interface {
	// 优惠券相关
	CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CouponReply, error)
	ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsReply, error)
	GrantCoupon(ctx context.Context, in *GrantCouponRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UseCoupon(ctx context.Context, in *UseCouponRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 计算优惠价格
	CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountReply, error)
}

type promotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionServiceClient(cc grpc.ClientConnInterface) PromotionServiceClient {
	return &promotionServiceClient{cc}
}

func (c *promotionServiceClient) CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CouponReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponReply)
	err := c.cc.Invoke(ctx, PromotionService_CreateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponsReply)
	err := c.cc.Invoke(ctx, PromotionService_ListCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) GrantCoupon(ctx context.Context, in *GrantCouponRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PromotionService_GrantCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) UseCoupon(ctx context.Context, in *UseCouponRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PromotionService_UseCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateDiscountReply)
	err := c.cc.Invoke(ctx, PromotionService_CalculateDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServiceServer is the server API for PromotionService service.
// All implementations must embed UnimplementedPromotionServiceServer
// for forward compatibility.
//
// 营销服务定义
type PromotionServiceServer interface {
	// 优惠券相关
	CreateCoupon(context.Context, *CreateCouponRequest) (*CouponReply, error)
	ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsReply, error)
	GrantCoupon(context.Context, *GrantCouponRequest) (*emptypb.Empty, error)
	UseCoupon(context.Context, *UseCouponRequest) (*emptypb.Empty, error)
	// 计算优惠价格
	CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountReply, error)
	mustEmbedUnimplementedPromotionServiceServer()
}

// UnimplementedPromotionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromotionServiceServer struct{}

func (UnimplementedPromotionServiceServer) CreateCoupon(context.Context, *CreateCouponRequest) (*CouponReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCoupon not implemented")
}
func (UnimplementedPromotionServiceServer) ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCoupons not implemented")
}
func (UnimplementedPromotionServiceServer) GrantCoupon(context.Context, *GrantCouponRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantCoupon not implemented")
}
func (UnimplementedPromotionServiceServer) UseCoupon(context.Context, *UseCouponRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UseCoupon not implemented")
}
func (UnimplementedPromotionServiceServer) CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateDiscount not implemented")
}
func (UnimplementedPromotionServiceServer) mustEmbedUnimplementedPromotionServiceServer() {}
func (UnimplementedPromotionServiceServer) testEmbeddedByValue()                          {}

// UnsafePromotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionServiceServer will
// result in compilation errors.
type UnsafePromotionServiceServer interface {
	mustEmbedUnimplementedPromotionServiceServer()
}

func RegisterPromotionServiceServer(s grpc.ServiceRegistrar, srv PromotionServiceServer) {
	// If the following call panics, it indicates UnimplementedPromotionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromotionService_ServiceDesc, srv)
}

func _PromotionService_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_CreateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).CreateCoupon(ctx, req.(*CreateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_ListCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).ListCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_ListCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).ListCoupons(ctx, req.(*ListCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_GrantCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).GrantCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_GrantCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).GrantCoupon(ctx, req.(*GrantCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_UseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).UseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_UseCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).UseCoupon(ctx, req.(*UseCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_CalculateDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).CalculateDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_CalculateDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).CalculateDiscount(ctx, req.(*CalculateDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromotionService_ServiceDesc is the grpc.ServiceDesc for PromotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promotion.v1.PromotionService",
	HandlerType: (*PromotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoupon",
			Handler:    _PromotionService_CreateCoupon_Handler,
		},
		{
			MethodName: "ListCoupons",
			Handler:    _PromotionService_ListCoupons_Handler,
		},
		{
			MethodName: "GrantCoupon",
			Handler:    _PromotionService_GrantCoupon_Handler,
		},
		{
			MethodName: "UseCoupon",
			Handler:    _PromotionService_UseCoupon_Handler,
		},
		{
			MethodName: "CalculateDiscount",
			Handler:    _PromotionService_CalculateDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/promotion/v1/promotion.proto",
}
