// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/promotion/v1/promotion.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CouponReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`           // 1: 满减, 2: 折扣
	Threshold     int64                  `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"` // 门槛金额
	Discount      int64                  `protobuf:"varint,5,opt,name=discount,proto3" json:"discount,omitempty"`   // 优惠金额或折扣比例
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponReply) Reset() {
	*x = CouponReply{}
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponReply) ProtoMessage() {}

func (x *CouponReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponReply.ProtoReflect.Descriptor instead.
func (*CouponReply) Descriptor() ([]byte, []int) {
	return file_api_promotion_v1_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *CouponReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponReply) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponReply) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CouponReply) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CouponReply) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CouponReply) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Threshold     int64                  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Discount      int64                  `protobuf:"varint,4,opt,name=discount,proto3" json:"discount,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCouponRequest) Reset() {
	*x = CreateCouponRequest{}
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponRequest) ProtoMessage() {}

func (x *CreateCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponRequest.ProtoReflect.Descriptor instead.
func (*CreateCouponRequest) Descriptor() ([]byte, []int) {
	return file_api_promotion_v1_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCouponRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCouponRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateCouponRequest) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateCouponRequest) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CreateCouponRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateCouponRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ListCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int32                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsRequest) Reset() {
	*x = ListCouponsRequest{}
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsRequest) ProtoMessage() {}

func (x *ListCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsRequest.ProtoReflect.Descriptor instead.
func (*ListCouponsRequest) Descriptor() ([]byte, []int) {
	return file_api_promotion_v1_promotion_proto_rawDescGZIP(), []int{2}
}

func (x *ListCouponsRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListCouponsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCouponsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CouponReply         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsReply) Reset() {
	*x = ListCouponsReply{}
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsReply) ProtoMessage() {}

func (x *ListCouponsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsReply.ProtoReflect.Descriptor instead.
func (*ListCouponsReply) Descriptor() ([]byte, []int) {
	return file_api_promotion_v1_promotion_proto_rawDescGZIP(), []int{3}
}

func (x *ListCouponsReply) GetResults() []*CouponReply {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListCouponsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GrantCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int64                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantCouponRequest) Reset() {
	*x = GrantCouponRequest{}
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantCouponRequest) ProtoMessage() {}

func (x *GrantCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantCouponRequest.ProtoReflect.Descriptor instead.
func (*GrantCouponRequest) Descriptor() ([]byte, []int) {
	return file_api_promotion_v1_promotion_proto_rawDescGZIP(), []int{4}
}

func (x *GrantCouponRequest) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *GrantCouponRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UseCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int64                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponRequest) Reset() {
	*x = UseCouponRequest{}
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponRequest) ProtoMessage() {}

func (x *UseCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponRequest.ProtoReflect.Descriptor instead.
func (*UseCouponRequest) Descriptor() ([]byte, []int) {
	return file_api_promotion_v1_promotion_proto_rawDescGZIP(), []int{5}
}

func (x *UseCouponRequest) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *UseCouponRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UseCouponRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CalculateDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CouponIds     []int64                `protobuf:"varint,3,rep,packed,name=coupon_ids,json=couponIds,proto3" json:"coupon_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDiscountRequest) Reset() {
	*x = CalculateDiscountRequest{}
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDiscountRequest) ProtoMessage() {}

func (x *CalculateDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDiscountRequest.ProtoReflect.Descriptor instead.
func (*CalculateDiscountRequest) Descriptor() ([]byte, []int) {
	return file_api_promotion_v1_promotion_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateDiscountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CalculateDiscountRequest) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CalculateDiscountRequest) GetCouponIds() []int64 {
	if x != nil {
		return x.CouponIds
	}
	return nil
}

type CalculateDiscountReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DiscountAmount int64                  `protobuf:"varint,1,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	FinalAmount    int64                  `protobuf:"varint,2,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculateDiscountReply) Reset() {
	*x = CalculateDiscountReply{}
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDiscountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDiscountReply) ProtoMessage() {}

func (x *CalculateDiscountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotion_v1_promotion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDiscountReply.ProtoReflect.Descriptor instead.
func (*CalculateDiscountReply) Descriptor() ([]byte, []int) {
	return file_api_promotion_v1_promotion_proto_rawDescGZIP(), []int{7}
}

func (x *CalculateDiscountReply) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CalculateDiscountReply) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

var File_api_promotion_v1_promotion_proto protoreflect.FileDescriptor

const file_api_promotion_v1_promotion_proto_rawDesc = "" +
	"\n" +
	" api/promotion/v1/promotion.proto\x12\fpromotion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf1\x01\n" +
	"\vCouponReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x03R\tthreshold\x12\x1a\n" +
	"\bdiscount\x18\x05 \x01(\x03R\bdiscount\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xe9\x01\n" +
	"\x13CreateCouponRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x03R\tthreshold\x12\x1a\n" +
	"\bdiscount\x18\x04 \x01(\x03R\bdiscount\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"L\n" +
	"\x12ListCouponsRequest\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"]\n" +
	"\x10ListCouponsReply\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.promotion.v1.CouponReplyR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"J\n" +
	"\x12GrantCouponRequest\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x03R\bcouponId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"c\n" +
	"\x10UseCouponRequest\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x03R\bcouponId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"u\n" +
	"\x18CalculateDiscountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"coupon_ids\x18\x03 \x03(\x03R\tcouponIds\"d\n" +
	"\x16CalculateDiscountReply\x12'\n" +
	"\x0fdiscount_amount\x18\x01 \x01(\x03R\x0ediscountAmount\x12!\n" +
	"\ffinal_amount\x18\x02 \x01(\x03R\vfinalAmount2\xa2\x03\n" +
	"\x10PromotionService\x12L\n" +
	"\fCreateCoupon\x12!.promotion.v1.CreateCouponRequest\x1a\x19.promotion.v1.CouponReply\x12O\n" +
	"\vListCoupons\x12 .promotion.v1.ListCouponsRequest\x1a\x1e.promotion.v1.ListCouponsReply\x12G\n" +
	"\vGrantCoupon\x12 .promotion.v1.GrantCouponRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\tUseCoupon\x12\x1e.promotion.v1.UseCouponRequest\x1a\x16.google.protobuf.Empty\x12a\n" +
	"\x11CalculateDiscount\x12&.promotion.v1.CalculateDiscountRequest\x1a$.promotion.v1.CalculateDiscountReplyB'Z%promotion-service/api/promotion/v1;v1b\x06proto3"

var (
	file_api_promotion_v1_promotion_proto_rawDescOnce sync.Once
	file_api_promotion_v1_promotion_proto_rawDescData []byte
)

func file_api_promotion_v1_promotion_proto_rawDescGZIP() []byte {
	file_api_promotion_v1_promotion_proto_rawDescOnce.Do(func() {
		file_api_promotion_v1_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_promotion_v1_promotion_proto_rawDesc), len(file_api_promotion_v1_promotion_proto_rawDesc)))
	})
	return file_api_promotion_v1_promotion_proto_rawDescData
}

var file_api_promotion_v1_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_promotion_v1_promotion_proto_goTypes = []any{
	(*CouponReply)(nil),              // 0: promotion.v1.CouponReply
	(*CreateCouponRequest)(nil),      // 1: promotion.v1.CreateCouponRequest
	(*ListCouponsRequest)(nil),       // 2: promotion.v1.ListCouponsRequest
	(*ListCouponsReply)(nil),         // 3: promotion.v1.ListCouponsReply
	(*GrantCouponRequest)(nil),       // 4: promotion.v1.GrantCouponRequest
	(*UseCouponRequest)(nil),         // 5: promotion.v1.UseCouponRequest
	(*CalculateDiscountRequest)(nil), // 6: promotion.v1.CalculateDiscountRequest
	(*CalculateDiscountReply)(nil),   // 7: promotion.v1.CalculateDiscountReply
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 9: google.protobuf.Empty
}
var file_api_promotion_v1_promotion_proto_depIdxs = []int32{
	8,  // 0: promotion.v1.CouponReply.start_time:type_name -> google.protobuf.Timestamp
	8,  // 1: promotion.v1.CouponReply.end_time:type_name -> google.protobuf.Timestamp
	8,  // 2: promotion.v1.CreateCouponRequest.start_time:type_name -> google.protobuf.Timestamp
	8,  // 3: promotion.v1.CreateCouponRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 4: promotion.v1.ListCouponsReply.results:type_name -> promotion.v1.CouponReply
	1,  // 5: promotion.v1.PromotionService.CreateCoupon:input_type -> promotion.v1.CreateCouponRequest
	2,  // 6: promotion.v1.PromotionService.ListCoupons:input_type -> promotion.v1.ListCouponsRequest
	4,  // 7: promotion.v1.PromotionService.GrantCoupon:input_type -> promotion.v1.GrantCouponRequest
	5,  // 8: promotion.v1.PromotionService.UseCoupon:input_type -> promotion.v1.UseCouponRequest
	6,  // 9: promotion.v1.PromotionService.CalculateDiscount:input_type -> promotion.v1.CalculateDiscountRequest
	0,  // 10: promotion.v1.PromotionService.CreateCoupon:output_type -> promotion.v1.CouponReply
	3,  // 11: promotion.v1.PromotionService.ListCoupons:output_type -> promotion.v1.ListCouponsReply
	9,  // 12: promotion.v1.PromotionService.GrantCoupon:output_type -> google.protobuf.Empty
	9,  // 13: promotion.v1.PromotionService.UseCoupon:output_type -> google.protobuf.Empty
	7,  // 14: promotion.v1.PromotionService.CalculateDiscount:output_type -> promotion.v1.CalculateDiscountReply
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_promotion_v1_promotion_proto_init() }
func file_api_promotion_v1_promotion_proto_init() {
	if File_api_promotion_v1_promotion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_promotion_v1_promotion_proto_rawDesc), len(file_api_promotion_v1_promotion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_promotion_v1_promotion_proto_goTypes,
		DependencyIndexes: file_api_promotion_v1_promotion_proto_depIdxs,
		MessageInfos:      file_api_promotion_v1_promotion_proto_msgTypes,
	}.Build()
	File_api_promotion_v1_promotion_proto = out.File
	file_api_promotion_v1_promotion_proto_goTypes = nil
	file_api_promotion_v1_promotion_proto_depIdxs = nil
}
