// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"product-service/internal/biz"
	"product-service/internal/conf"
	"product-service/internal/data"
	"product-service/internal/server"
	"product-service/internal/service"
)

// Injectors from wire.go:

func wireApp(config *conf.Config, logger log.Logger) (*kratos.App, func(), error) {
	confData := data.ProvideDataConfig(config)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(dataData, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	discovery := data.NewDiscovery(config)
	string2 := data.ProvideInventoryEndpoint(config)
	inventoryRepo := data.NewInventoryRepo(discovery, string2, logger)
	productUseCase := biz.NewProductUseCase(productRepo, categoryRepo, inventoryRepo, logger)
	productService := service.NewProductService(productUseCase)
	grpcServer := server.NewGRPCServer(config, productService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
