// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"promotion-service/internal/biz"
	"promotion-service/internal/conf"
	"promotion-service/internal/data"
	"promotion-service/internal/server"
	"promotion-service/internal/service"
)

// Injectors from wire.go:

func wireApp(config *conf.Config, logger log.Logger) (*kratos.App, func(), error) {
	confData := data.ProvideDataConfig(config)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	promotionRepo := data.NewPromotionRepo(dataData, logger)
	promotionUseCase := biz.NewPromotionUseCase(promotionRepo, logger)
	promotionService := service.NewPromotionService(promotionUseCase)
	grpcServer := server.NewGRPCServer(config, promotionService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
